# Generated by Django 3.0.3 on 2020-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('timestamp', models.DateTimeField(blank=True)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
